global:
  scrape_interval: 5s
  external_labels:
    monitor: 'Monitoring'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['144.24.110.41:9090']

  - job_name: 'Jenkins-Server-9100'  # Unique job name
    static_configs:
      - targets: ['144.24.110.41:9100']

  - job_name: 'Jenkins-Server-8181'  # Unique job name
    static_configs:
      - targets: ['144.24.110.41:8181']

  - job_name: 'App-Server-9100'  # Unique job name
    static_configs:
      - targets: ['150.230.233.13:9100']

  # Add more job configurations if needed



====================================================

global:
  scrape_interval: 5s
  external_labels:
    monitor: 'Monitoring'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['144.24.110.41:9090']
  - job_name: 'Jenkins-Server'
    static_configs:
      - targets: ['144.24.110.41:9100']
  - job_name: 'Jenkins-Server'
    static_configs:
      - targets: ['144.24.110.41:8181']
#App-Testing server
  - job_name: 'App-Server'
    static_configs:
      - targets: ['150.230.233.13:9100']
  - job_name: 'App-Server'
    static_configs:
      - targets: ['150.230.233.13:8181']


